[package]
name = "rs-pmd98-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
encoding_rs = { version = "0.8.35", features = ["fast-kanji-encode", "serde"] }
strum = { version = "0.27.1", features = ["derive"] }
thiserror = "2.0.12"
